<<<<<<< HEAD
# Generated by Django 2.2 on 2019-12-17 23:08
=======
# Generated by Django 2.2 on 2021-01-27 13:40
>>>>>>> bb8adc725cc29a5ab85a0d2219a704e0efe8bd24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('tweets', '0004_auto_20191217_1953'),
=======
        ('tweets', '0004_auto_20210127_1238'),
>>>>>>> bb8adc725cc29a5ab85a0d2219a704e0efe8bd24
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tweets.Tweet'),
        ),
    ]
